CREATE TABLE IF NOT EXISTS LOAISP (
    MALOAI CHAR(8) PRIMARY KEY,
    TENLOAI VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS SANPHAM (
    MASP CHAR(8) PRIMARY KEY,
    TENSP VARCHAR(50),
    DVT VARCHAR(20),
    GIANHAP FLOAT,
    MALOAI CHAR(8),
    SOLUONG_TON FLOAT,

    CONSTRAINT fk_sanpham_loaisp
        FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI)
);

CREATE TABLE IF NOT EXISTS DOITAC (
    MADT CHAR(8) PRIMARY KEY,
    TENDT VARCHAR(50),
    DCHI VARCHAR(100),
    SDT VARCHAR(11),
    LOAIDT INT
);

CREATE TABLE IF NOT EXISTS NHANVIEN (
    MANV CHAR(8) PRIMARY KEY,
    TENNV VARCHAR(50),
    DCHI VARCHAR(100),
    SDT VARCHAR(11),
    LOAINV INT
);

CREATE TABLE IF NOT EXISTS PHIEUNHAP (
    MAPN CHAR(8) PRIMARY KEY,
    NGAYNHAP DATE,
    MANV CHAR(8),
    MADT CHAR(8),

    CONSTRAINT fk_phieunhap_nhanvien
        FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),

    CONSTRAINT fk_phieunhap_doitac
        FOREIGN KEY (MADT) REFERENCES DOITAC(MADT)
);

CREATE TABLE IF NOT EXISTS CT_PHIEUNHAP (
    MAPN CHAR(8),
    MASP CHAR(8),
    SOLUONG FLOAT,
    DONGIA FLOAT,

    CONSTRAINT pk_ct_phieunhap PRIMARY KEY (MAPN, MASP),

    CONSTRAINT fk_ct_phieunhap_phieunhap
        FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),

    CONSTRAINT fk_ct_phieunhap_sanpham
        FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE IF NOT EXISTS PHIEUXUAT (
    MAPX CHAR(8) PRIMARY KEY,
    NGAYXUAT DATE,
    MANV CHAR(8),
    MADT CHAR(8),

    CONSTRAINT fk_phieuxuat_nhanvien
        FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),

    CONSTRAINT fk_phieuxuat_doitac
        FOREIGN KEY (MADT) REFERENCES DOITAC(MADT)
);

CREATE TABLE IF NOT EXISTS CT_PHIEUXUAT (
    MAPX CHAR(8),
    MASP CHAR(8),
    SOLUONG FLOAT,
    DONGIA FLOAT,

    CONSTRAINT pk_ct_phieuxuat PRIMARY KEY (MAPX, MASP),

    CONSTRAINT fk_ct_phieuxuat_phieuxuat
        FOREIGN KEY (MAPX) REFERENCES PHIEUXUAT(MAPX),

    CONSTRAINT fk_ct_phieuxuat_sanpham
        FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE IF NOT EXISTS PHIEUKIEMKE (
    MAPKK CHAR(8) PRIMARY KEY,
    NGAYKK DATE,
    MANV CHAR(8),
    GHICHU VARCHAR(250),

    CONSTRAINT fk_phieukiemke_nhanvien
        FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE IF NOT EXISTS CT_PHIEUKIEMKE (
    MAPKK CHAR(8),
    MASP CHAR(8),
    SL_HETHONG FLOAT,
    SL_THUCTE FLOAT,
    LYDO VARCHAR(250),

    CONSTRAINT pk_ct_phieukiemke PRIMARY KEY (MAPKK, MASP),

    CONSTRAINT fk_ct_phieukiemke_phieukiemke
        FOREIGN KEY (MAPKK) REFERENCES PHIEUKIEMKE(MAPKK),

    CONSTRAINT fk_ct_phieukiemke_sanpham
        FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);