ALTER TABLE NHANVIEN
ADD CONSTRAINT kiem_tra_loai_nv
CHECK (LOAINV IN (0, 1, 2));

ALTER TABLE DOITAC
ADD CONSTRAINT kiem_tra_loai_dt
CHECK (LOAIDT IN (0, 1, 2));

ALTER TABLE SANPHAM
ADD CONSTRAINT kiem_tra_so_luong_ton_kho
CHECK (SOLUONG_TON >= 0);

ALTER TABLE CT_PHIEUNHAP
ADD CONSTRAINT kiem_tra_so_luong_don_gia_nhap
CHECK (SOLUONG > 0 AND DONGIA > 0);

ALTER TABLE CT_PHIEUXUAT
ADD CONSTRAINT kiem_tra_so_luong_don_gia_xuat
CHECK (SOLUONG > 0 AND DONGIA > 0);