CREATE TABLE IF NOT EXISTS TAIKHOAN (
    EMAIL VARCHAR(100) PRIMARY KEY,
    MATKHAU VARCHAR(100) NOT NULL,
    HOTEN VARCHAR(50) NOT NULL,
    MANV CHAR(8) NOT NULL UNIQUE,
    LOAINV INT NOT NULL,
    NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_taikhoan_nhanvien
        FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),

    CONSTRAINT kiem_tra_taikhoan_loainv
        CHECK (LOAINV IN (0, 1, 2))
);

INSERT INTO TAIKHOAN (EMAIL, MATKHAU, HOTEN, MANV, LOAINV) VALUES
('quanly@ie103.local', '123456', 'Nhóm Quản lý', 'NVQL0001', 0),
('nhapkho@ie103.local', '123456', 'Nhóm NV Nhập kho', 'NVNH0001', 1),
('xuatkho@ie103.local', '123456', 'Nhóm NV Xuất kho', 'NVXU0001', 2)
ON CONFLICT (EMAIL) DO NOTHING;
